version: "3.8"

services:
  competence-sync-db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pgisready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  competence-sync-backend:
    image: mta2003/competence-sync-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      competence-sync-db:
        condition: service_completed_successfully

volumes:
  pgdata: