version: "3.8"
name: compose-for-dev
services:
  competence-sync-db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env.dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}