"""fix_competence_id_pk

Revision ID: 92b95dd86707
Revises: e9dbe413a576
Create Date: 2025-04-05 23:01:17.046512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92b95dd86707'
down_revision: Union[str, None] = 'e9dbe413a576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_competencies_competence_id_fkey', 'user_competencies', type_='foreignkey')
    op.alter_column('competencies', 'id',
                    existing_type=sa.UUID(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=False)
    op.create_index(op.f('ix_competencies_id'), 'competencies', ['id'], unique=False)
    op.alter_column('user_competencies', 'level',
                    existing_type=sa.NUMERIC(precision=5, scale=3),
                    nullable=False)

    op.alter_column('user_competencies', 'competence_id',
                    existing_type=sa.UUID(),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=False)

    op.create_foreign_key(
        'user_competencies_competence_id_fkey',
        'user_competencies', 'competencies',
        ['competence_id'], ['id']
    )

    op.drop_index('id_user_competence', table_name='user_competencies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_user_competence', 'user_competencies', ['user_id', 'competence_id'], unique=True)

    op.drop_constraint('user_competencies_competence_id_fkey', 'user_competencies', type_='foreignkey')

    op.alter_column('user_competencies', 'competence_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               postgresql_using='competence_id::uuid',
               existing_nullable=False)
    op.alter_column('user_competencies', 'level',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               nullable=True)
    op.drop_index(op.f('ix_competencies_id'), table_name='competencies')
    op.alter_column('competencies', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               postgresql_using='id::uuid',
               existing_nullable=False)

    op.create_foreign_key(
        'user_competencies_competence_id_fkey',
        'user_competencies', 'competencies',
        ['competence_id'], ['id']
    )

    # ### end Alembic commands ###
