"""add_vacancy_competencies_and_resume

Revision ID: ccc08697bd73
Revises: 92b95dd86707
Create Date: 2025-04-05 23:43:49.539691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ccc08697bd73'
down_revision: Union[str, None] = '92b95dd86707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emails', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('phones', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_first_name'), 'resumes', ['first_name'], unique=False)
    op.create_index(op.f('ix_resumes_last_name'), 'resumes', ['last_name'], unique=False)
    op.create_table('resume_competence',
    sa.Column('level', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('competence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('resume_id', 'competence_id', name='resume_competence_pk')
    )
    op.create_table('vacancy_competencies',
    sa.Column('level', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('competence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vacancy_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('vacancy_id', 'competence_id', name='vacancy_competence_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_competencies')
    op.drop_table('resume_competence')
    op.drop_index(op.f('ix_resumes_last_name'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_first_name'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
