name: CI/CD

on:
  workflow_dispatch:
    branches: [prod]
  push:
    branches: [prod]
env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_LOGIN }}/competence-sync-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: 3.10.11
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: | 
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
            
      - name: Verify deployment
        run: |
          echo "Successfully built and pushed:"
          echo "${{ env.DOCKER_IMAGE }}:latest"
          echo "${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
      
            
      
